function(add_qt_test name)
    add_executable(${name} ${name}.cpp)
    target_link_libraries(${name} PRIVATE artillery_core artillery_coreplugin Qt6::Test Qt6::Quick Qt6::QuickTest)
    add_test(NAME ${name} COMMAND ${name})
    set_tests_properties(${name} PROPERTIES ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
endfunction()

add_qt_test(test_gameengine)
add_qt_test(test_physics)
add_qt_test(test_gameboard)
add_qt_test(test_controls_binding)
add_qt_test(test_flight)
add_qt_test(test_ai)
add_qt_test(test_gameloop)
